
# Travis CI configuration for Ops Team Topic Updater.
#
# @see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# @see https://docs.travis-ci.com/user/database-setup/#postgresql
# @author Tim Malone <tdmalone@gmail.com>

language: node_js
node_js: 10.8.0

cache:
  yarn: true
  directories:
    - node_modules

before_install:

  # Upgrade Yarn to the version specified in package.json.
  - curl --location https://yarnpkg.com/install.sh | bash -s -- --version "$( node -e "console.log(require('./package.json').engines.yarn)" )"
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile

script:
  - yarn lint
  - yarn test

# On success, deployments are automatically handled by Heroku.
